In [1]:
import sqlite3 as sq3
import csv
import pandas as pd

In [2]:
#koneksi ke database
conn = sq3.connect('abusive_text.db')

#membuat objek cursor
cursor = conn.cursor()

#query untuk membuat table
sql = "CREATE TABLE IF NOT EXISTS ABUSIVE(teks CHAR(20) NOT NULL)"
cursor.execute(sql)

sql = "CREATE TABLE IF NOT EXISTS ALAY(teks_alay CHAR(100) NOT NULL, teks_baku CHAR(100) NOT NULL)"
cursor.execute(sql)

#sebelum memasukkan data csv ke tabel pastikan bahwa tabel kosong
sql = "DELETE FROM ABUSIVE"
cursor.execute(sql)

sql = "DELETE FROM ALAY"
cursor.execute(sql)

# masukkan data csv kedalam table abusive
file = open('dataset_gold/abusive.csv')
contents = csv.reader(file)
insert_records = "INSERT INTO ABUSIVE (teks) VALUES(?)"
cursor.executemany(insert_records, contents)


# masukkan data csv kedalam table alay
file = open('dataset_gold/new_kamusalay.csv')
contents = csv.reader(file)
insert_records = "INSERT INTO ALAY (teks_alay,teks_baku) VALUES(?,?)"
cursor.executemany(insert_records, contents)

# cek isi tabel abusive
select_all = "SELECT * FROM ABUSIVE"
rows_abusive = cursor.execute(select_all).fetchall()

# menampilkan data yg sudah diinsert
df_abusive = pd.read_sql_query("select * from ABUSIVE", conn)
df_alay = pd.read_sql_query("select * from ALAY", conn)


# commit perubahan
conn.commit()

#tutup koneksi
conn.close()

In [3]:
# df_abusive = df_abusive.to_dict(orient='dict')
df_abusive

            teks
0        ABUSIVE
1           alay
2          ampas
3           buta
4        keparat
..           ...
121        rezim
122        sange
123       serbet
124        sipit
125  transgender

[126 rows x 1 columns]

In [4]:
# dict_alay = dict(zip(df_alay['teks_alay'],df_alay['teks_baku']))
# bool('asdsad' in dict_alay)

df_alay

                 teks_alay                          teks_baku
0      anakjakartaasikasik           anak jakarta asyik asyik
1             pakcikdahtua                  pak cik sudah tua
2           pakcikmudalagi                  pak cik muda lagi
3              t3tapjokowi                       tetap jokowi
4                       3x                          tiga kali
...                    ...                                ...
15162            mendikbud  menteri pendidikan dan kebudayaan
15163               mendag                menteri perdagangan
15164              menaker               menteri tenaga kerja
15165             memetwit                            mentwit
15166             megangin                           memegang

[15167 rows x 2 columns]

In [6]:
try:
     
    # Making a connection between sqlite3
    # database and Python Program
    sqliteConnection = sq3.connect('abusive_text.db')
     
    # If sqlite3 makes a connection with python
    # program then it will print "Connected to SQLite"
    # Otherwise it will show errors
    print("Connected to SQLite")
 
    # Getting all tables from sqlite_master
    sql_query = """SELECT name FROM sqlite_master
    WHERE type='table';"""
 
    # Creating cursor object using connection object
    cursor = sqliteConnection.cursor()
     
    # executing our sql query
    cursor.execute(sql_query)
    print("List of tables\n")
     
    # printing all tables list
    print(cursor.fetchall())
 
except sq3.Error as error:
    print("Failed to execute the above query", error)
     
finally:
   
    # Inside Finally Block, If connection is
    # open, we need to close it
    if sqliteConnection:
         
        # using close() method, we will close
        # the connection
        sqliteConnection.close()
         
        # After closing connection object, we
        # will print "the sqlite connection is
        # closed"
        print("the sqlite connection is closed")

Connected to SQLite
List of tables

[('ABUSIVE',), ('ALAY',)]
the sqlite connection is closed

In [6]:
df_data = pd.read_csv('dataset_gold/data.csv')
df_data

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 1389: invalid continuation byte